# Site settings
title: Prateek Verma
description: Mathematical modelling of gene drives and eco‑evolutionary dynamics.
url: "https://prateek1verma.github.io"   # change if using a custom domain
baseurl: ""                               # repo is <username>.github.io → keep empty
timezone: America/Los_Angeles

author:
  name: Prateek Verma
  email: prateekverma@berkeley.edu
  affiliation: UC Berkeley — School of Public Health (Marshall Lab)
  scholar: https://scholar.google.com/citations?user=2RaZWAkAAAAJ
  linkedin: https://www.linkedin.com/in/prateek1science
  researchgate: https://www.researchgate.net/profile/Prateek-Verma-16

# Build settings
markdown: kramdown
theme: null          # use our custom layout/styles
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections & defaults (optional)
defaults:
  - scope: {path: ""}
    values:
      layout: default

# Feed & SEO
feed:
  path: feed.xml

# Navigation (used by navbar)
nav:
  - name: Home
    url: /
  - name: Research Focus
    url: /research
  - name: Publications
    url: /publications
  - name: People
    url: /people
  - name: Contact
    url: /contact
